### ISSUE TITLE
Esto como se usa

### ISSUE THREAD

**Issue by Salty-cinders** [ziul9/IJR-DS#1]
lol xd jajajajajajaja

**Comment by Skiwex** [comment]
malparido hijueputa gonorrea asbesto de la humanidad

**Comment by Skiwex** [comment]
adefesio

**Comment by Skiwex** [comment]
dotor uribe

**Comment by Skiwex** [comment]
# señor nooooooooooooooooooooooooooo jesusjesus no me castigue

**Comment by Salty-cinders** [comment]
embidiozo

**Comment by Skiwex** [comment]
mozo mui emvidio$o

**Comment by Skiwex** [comment]
@Salty-cinders putha

**Comment by Salty-cinders** [comment]
vhovo no save ke tru mas folz da uno ke idihoto

**Comment by Salty-cinders** [comment]
``bas

**Comment by Salty-cinders** [comment]
hHIT HIT HIT EL PASADO DE HIT ES HIT IDIOTO

**Comment by Skiwex** [comment]
bengase pues sannntos que le pego en esa cara marika

**Comment by Skiwex** [comment]
icuandocorrea
